from app.core.logger import log_event
from app.tools.file_utils import commit_and_push
from app.tools.github import create_pr


def reviewer_agent(state):

    approved = state["tests"]["status"] == "pass"
    state["review"]["approved"] = approved

    if approved:
        branch_name = "ai-fix-login-bug"

        repo_path = state["context"]["repo_path"]

        print("🚀 Starting commit & push...")

        commit_and_push(repo_path, branch_name)

        # 🔥 FIXED INDENTATION
        owner, repo = state["issue"]["repo"].split("/")

        pr = create_pr(
            owner=owner,
            repo=repo,
            branch=branch_name,
            title="AI Fix: " + state["issue"]["title"],
            body="This PR was automatically generated by AI Engineer Agent."
        )

        if pr:
            print("🔗 PR created:", pr.get("html_url"))
        else:
            print("❌ PR creation failed")

        print(f"✅ Issue resolved in {state['meta']['iteration_count']} iterations")

        state["status"] = "success"

    else:
        print("❌ Solution failed review")
        state["status"] = "failed"

    log_event({
        "agent": "reviewer",
        "approved": approved
    })

    return state